# External Configuration
spring.config.import=optional:file:config/mail.properties

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/pricetracker
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema_v1.sql

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Model Product Configuration
model.product.url=${MODEL_PRODUCT_URL}

# Firebase Configuration
firebase.config.path=config/firebase-service-account.json